steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.api
      - -t
      - europe-west1-docker.pkg.dev/mental-health-signal-detector/mental-health-api/api:latest
      - .

images:
  - europe-west1-docker.pkg.dev/mental-health-signal-detector/mental-health-api/api:latest
