FROM python:3.11-slim

WORKDIR /app
ENV PYTHONPATH=/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m nltk.downloader stopwords wordnet averaged_perceptron_tagger averaged_perceptron_tagger_eng punkt punkt_tab
COPY src/ ./src/
COPY models/ ./models/

EXPOSE 8000


CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
