FROM python:3.11-slim
LABEL author="Aimen"

RUN apt-get update

RUN apt-get install -y iputils-ping

WORKDIR /app
ENV PYTHONPATH=/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ ./src/
COPY models/ ./models/

EXPOSE 8000


CMD ["bash", "-c", "uvicorn src.api.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
